// AUTO-GENERATED by scripts/extract-farming.py — DO NOT EDIT.
// Source: DST scripts/prefabs/{farm_plant_defs,weed_defs,veggies,fertilizer_nutrient_defs}.lua + tuning.lua + ko.po
// 갱신: bash scripts/sync-game-data.sh

export type FarmSeason = "spring" | "summer" | "autumn" | "winter";
export type FarmDrinkLevel = "low" | "med" | "high";
export type FarmStressGradeId = "none" | "low" | "moderate" | "high";
export type FarmStressorId = "nutrients" | "moisture" | "killjoys" | "season" | "family" | "overcrowding" | "happiness";
/** [성장 촉진제, 퇴비, 거름] — TUNING.FORMULA/COMPOST/MANURE_NUTRIENTS_INDEX = 1/2/3 */
export type FarmNutrients = [number, number, number];
export interface FarmText { en: string; ko: string }

export interface FarmCrop {
  id: string;
  /** 성장 단계가 넘어갈 때마다 타일에서 가져가는 양분 */
  consume: FarmNutrients;
  /** 같은 시점에 타일로 되돌리는 양분 (소비 총량을 소비하지 않는 양분에 균등 분배) */
  restore: FarmNutrients;
  seasons: FarmSeason[];
  drinkLevel: FarmDrinkLevel;
  /** 포기당 초당 수분 소비 (성장 중일 때만) */
  drinkRate: number;
  /** 초 단위 [min, max]. full 은 싹 50% · 작음 30% · 중간 20% 로 나뉜다 */
  growTime: { germination: [number, number]; full: [number, number] };
  /** 일반 씨앗에서 뽑힐 가중치 (제철이면 × seedWeightSeasonMod) */
  seedWeight: number;
  name: FarmText;
  seedId: string;
  seedName: FarmText;
  /** 도감에 등록하기 전 씨앗 모양 이름 */
  unknownSeedName: FarmText;
  oversizedId: string;
  oversizedName: FarmText;
  plantName: FarmText;
  description: FarmText;
}

export interface FarmWeed {
  id: string;
  seedWeight: number;
  consume: FarmNutrients;
  drinkLevel: FarmDrinkLevel;
  drinkRate: number;
  productId: string | null;
  name: FarmText;
  effect: FarmText;
}

export interface FarmFertilizer { id: string; nutrients: FarmNutrients; uses: number; image: string; name: FarmText }
export interface FarmTendTool { id: string; name: FarmText; range: number; tiles: number }
export interface FarmWaterSource { id: string; name: FarmText; amount: number; uses: number }

export const FARM_SEASONS: FarmSeason[] = ["spring", "summer", "autumn", "winter"];

export const FARM_CONSTANTS = {
  "consumeLow": 2,
  "consumeMed": 4,
  "consumeHigh": 8,
  "drinkLow": 0.0075,
  "drinkMed": 0.02,
  "drinkHigh": 0.035,
  "droughtTolerance": 0.1,
  "killjoyRadius": 6,
  "killjoyTolerance": 0,
  "familyMin": 4,
  "familyRadius": 4,
  "overcrowdingMaxPlants": 10,
  "startingNutrientsMin": 20,
  "startingNutrientsMax": 40,
  "randomSeedWeedChance": 0.2,
  "seedWeightSeasonMod": 2,
  "longLifeMult": 1.5,
  "oversizedPerishMult": 4,
  "perishGroundMult": 1.5,
  "soilRainMod": 1.5,
  "soilMaxTempDryRate": 0.05,
  "unitsPerTile": 4
} as const;

export const FARM_NUTRIENT_NAMES: [FarmText, FarmText, FarmText] = [
  {"en": "Growth Formula", "ko": "성장 촉진제"},
  {"en": "Compost", "ko": "퇴비"},
  {"en": "Manure", "ko": "거름"},
];

export const FARM_LABELS = {
  "plants": {
    "en": "Plants",
    "ko": "식물"
  },
  "fertilizers": {
    "en": "Fertilizers",
    "ko": "비료"
  },
  "seasons": {
    "en": "Seasons",
    "ko": "계절"
  },
  "water": {
    "en": "Water Consumption",
    "ko": "물 소비량"
  },
  "product": {
    "en": "Product",
    "ko": "생산물"
  },
  "seed": {
    "en": "Seed",
    "ko": "씨앗"
  },
  "nutrientCycling": {
    "en": "Nutrient Cycling",
    "ko": "양분 순환"
  },
  "fieldNotes": {
    "en": "Field Notes",
    "ko": "현장 기록"
  },
  "consume": {
    "en": "Consumes",
    "ko": "소비"
  },
  "restore": {
    "en": "Restores",
    "ko": "배출"
  },
  "effects": {
    "en": "Effects",
    "ko": "효과"
  },
  "randomSeeds": {
    "en": "Seeds",
    "ko": "씨앗"
  },
  "debris": {
    "en": "Garden Detritus",
    "ko": "텃밭 쓰레기"
  }
} as const;

export const FARM_CROPS: FarmCrop[] = [
  {"id": "carrot", "consume": [4, 0, 0], "restore": [0, 2, 2], "seasons": ["spring", "autumn", "winter"], "drinkLevel": "low", "drinkRate": 0.0075, "growTime": {"germination": [360, 480], "full": [1920, 3360]}, "seedWeight": 2.5, "name": {"en": "Carrot", "ko": "당근"}, "seedId": "carrot_seeds", "seedName": {"en": "Carrot Seeds", "ko": "당근 씨앗"}, "unknownSeedName": {"en": "Oblong Seeds", "ko": "길쭉 씨앗"}, "oversizedId": "carrot_oversized", "oversizedName": {"en": "Giant Carrots", "ko": "거대한 당근"}, "plantName": {"en": "Carrot Plant", "ko": "당근 뿌리"}, "description": {"en": "The perennial favorite of Bunnymen. -W", "ko": "토끼인간들이 사시사철 좋아하는 다년생 채소. -W"}},
  {"id": "corn", "consume": [0, 4, 0], "restore": [2, 0, 2], "seasons": ["spring", "summer", "autumn"], "drinkLevel": "low", "drinkRate": 0.0075, "growTime": {"germination": [360, 480], "full": [1920, 3360]}, "seedWeight": 2.5, "name": {"en": "Corn", "ko": "옥수수"}, "seedId": "corn_seeds", "seedName": {"en": "Corn Seeds", "ko": "옥수수 씨앗"}, "unknownSeedName": {"en": "Clustered Seeds", "ko": "씨앗 뭉치"}, "oversizedId": "corn_oversized", "oversizedName": {"en": "Giant Corn", "ko": "거대한 옥수수"}, "plantName": {"en": "Corn Stalk", "ko": "옥수수 대"}, "description": {"en": "An a-maize-ingly versatile crop. -W", "ko": "정말 '옥수'로 다재다능한 작물. -W"}},
  {"id": "potato", "consume": [0, 0, 4], "restore": [2, 2, 0], "seasons": ["spring", "autumn", "winter"], "drinkLevel": "low", "drinkRate": 0.0075, "growTime": {"germination": [360, 480], "full": [1920, 3360]}, "seedWeight": 2.5, "name": {"en": "Potato", "ko": "감자"}, "seedId": "potato_seeds", "seedName": {"en": "Potato Seeds", "ko": "감자 씨앗"}, "unknownSeedName": {"en": "Fluffy Seeds", "ko": "솜털 씨앗"}, "oversizedId": "potato_oversized", "oversizedName": {"en": "Giant Potato", "ko": "거대한 감자"}, "plantName": {"en": "Potato Plant", "ko": "감자 식물체"}, "description": {"en": "Sturdy, dependable, and loved by moustachioed strongmen. -W", "ko": "강인하고, 신뢰성 있으며, 콧수염 달린 차력사들이 좋아한다. -W"}},
  {"id": "tomato", "consume": [2, 2, 0], "restore": [0, 0, 4], "seasons": ["spring", "summer", "autumn"], "drinkLevel": "high", "drinkRate": 0.035, "growTime": {"germination": [360, 480], "full": [1920, 3360]}, "seedWeight": 2.5, "name": {"en": "Toma Root", "ko": "토마토란"}, "seedId": "tomato_seeds", "seedName": {"en": "Toma Root Seeds", "ko": "토마토란 씨앗"}, "unknownSeedName": {"en": "Spiky Seeds", "ko": "삐죽빼죽한 씨앗"}, "oversizedId": "tomato_oversized", "oversizedName": {"en": "Giant Toma Root", "ko": "거대한 토마토란"}, "plantName": {"en": "Toma Root Plant", "ko": "토마토란 식물체"}, "description": {"en": "Tomatoes are an excellent source of vitamins, and make for a convenient projectile. -W", "ko": "토마토는 훌륭한 비타민 공급원으로, 편리한 투척 무기로도 쓸 수 있다. -W"}},
  {"id": "asparagus", "consume": [0, 4, 0], "restore": [2, 0, 2], "seasons": ["spring", "winter"], "drinkLevel": "low", "drinkRate": 0.0075, "growTime": {"germination": [360, 480], "full": [1920, 3360]}, "seedWeight": 1.0, "name": {"en": "Asparagus", "ko": "아스파라거스"}, "seedId": "asparagus_seeds", "seedName": {"en": "Asparagus Seeds", "ko": "아스파라거스 씨앗"}, "unknownSeedName": {"en": "Tubular Seeds", "ko": "원통 씨앗"}, "oversizedId": "asparagus_oversized", "oversizedName": {"en": "Giant Asparagus", "ko": "거대한 아스파라거스"}, "plantName": {"en": "Asparagus Fern", "ko": "아스파라거스 줄기"}, "description": {"en": "Green spears of vegetabley goodness. -W", "ko": "식물성 영양분을 책임지는 녹색 기둥. -W"}},
  {"id": "eggplant", "consume": [0, 0, 4], "restore": [2, 2, 0], "seasons": ["spring", "autumn"], "drinkLevel": "med", "drinkRate": 0.02, "growTime": {"germination": [360, 480], "full": [1920, 3360]}, "seedWeight": 1.0, "name": {"en": "Eggplant", "ko": "가지"}, "seedId": "eggplant_seeds", "seedName": {"en": "Eggplant Seeds", "ko": "가지 씨앗"}, "unknownSeedName": {"en": "Swirly Seeds", "ko": "회오리 씨앗"}, "oversizedId": "eggplant_oversized", "oversizedName": {"en": "Giant Eggplant", "ko": "거대한 가지"}, "plantName": {"en": "Eggplant Stalk", "ko": "가지 줄기"}, "description": {"en": "Zero percent egg, ninety-nine percent plant. Science has yet to explain the rest. -W", "ko": "0 퍼센트 달걀, 99 퍼센트 식물. 나머지는 아직 과학으로 설명 불가. - W"}},
  {"id": "pumpkin", "consume": [4, 0, 0], "restore": [0, 2, 2], "seasons": ["autumn", "winter"], "drinkLevel": "med", "drinkRate": 0.02, "growTime": {"germination": [360, 480], "full": [1920, 3360]}, "seedWeight": 1.0, "name": {"en": "Pumpkin", "ko": "호박"}, "seedId": "pumpkin_seeds", "seedName": {"en": "Pumpkin Seeds", "ko": "호박 씨앗"}, "unknownSeedName": {"en": "Sharp Seeds", "ko": "날카로운 씨앗"}, "oversizedId": "pumpkin_oversized", "oversizedName": {"en": "Giant Pumpkin", "ko": "거대한 호박"}, "plantName": {"en": "Pumpkin Plant", "ko": "호박 식물체"}, "description": {"en": "Compared to other gourds, the pumpkin plant squashes the competition. -W", "ko": "다른 박 종류는 호박에 비하면 그저 애호박에 불과할 뿐이다. -W"}},
  {"id": "watermelon", "consume": [0, 2, 2], "restore": [4, 0, 0], "seasons": ["spring", "summer"], "drinkLevel": "high", "drinkRate": 0.035, "growTime": {"germination": [360, 480], "full": [1920, 3360]}, "seedWeight": 1.0, "name": {"en": "Watermelon", "ko": "수박"}, "seedId": "watermelon_seeds", "seedName": {"en": "Watermelon Seeds", "ko": "수박 씨앗"}, "unknownSeedName": {"en": "Square Seeds", "ko": "네모난 씨앗"}, "oversizedId": "watermelon_oversized", "oversizedName": {"en": "Giant Watermelon", "ko": "거대한 수박"}, "plantName": {"en": "Watermelon Plant", "ko": "수박 식물체"}, "description": {"en": "Fifty percent water, fifty percent melon. -W", "ko": "50% 물, 50% 박. -W"}},
  {"id": "dragonfruit", "consume": [0, 0, 8], "restore": [4, 4, 0], "seasons": ["spring", "summer"], "drinkLevel": "med", "drinkRate": 0.02, "growTime": {"germination": [360, 480], "full": [1920, 3360]}, "seedWeight": 0.5, "name": {"en": "Dragon Fruit", "ko": "용과"}, "seedId": "dragonfruit_seeds", "seedName": {"en": "Dragon Fruit Seeds", "ko": "용과 씨앗"}, "unknownSeedName": {"en": "Bulbous Seeds", "ko": "둥글납작 씨앗"}, "oversizedId": "dragonfruit_oversized", "oversizedName": {"en": "Giant Dragon Fruit", "ko": "거대한 용과"}, "plantName": {"en": "Dragon Fruit Vine", "ko": "용과 덩굴"}, "description": {"en": "Produces a delectable fruit with a striking appearance. -W", "ko": "매우 두드러지는 외형의 매력적인 열매를 맺는다. -W"}},
  {"id": "durian", "consume": [0, 8, 0], "restore": [4, 0, 4], "seasons": ["spring"], "drinkLevel": "low", "drinkRate": 0.0075, "growTime": {"germination": [360, 480], "full": [1920, 3360]}, "seedWeight": 0.5, "name": {"en": "Durian", "ko": "두리안"}, "seedId": "durian_seeds", "seedName": {"en": "Durian Seeds", "ko": "두리안 씨앗"}, "unknownSeedName": {"en": "Brittle Seed Pods", "ko": "바스락 씨앗 꼬투리"}, "oversizedId": "durian_oversized", "oversizedName": {"en": "Giant Durian", "ko": "거대한 두리안"}, "plantName": {"en": "Durian Vine", "ko": "두리안 덩굴"}, "description": {"en": "A foul smelling fruit, favored by a certain green swamp dweller. -W", "ko": "지독한 냄새가 나는 과일. 어떤 녹색 늪 생물이 매우 좋아한다. -W"}},
  {"id": "garlic", "consume": [0, 8, 0], "restore": [4, 0, 4], "seasons": ["spring", "summer", "autumn", "winter"], "drinkLevel": "low", "drinkRate": 0.0075, "growTime": {"germination": [360, 480], "full": [1920, 3360]}, "seedWeight": 0.5, "name": {"en": "Garlic", "ko": "마늘"}, "seedId": "garlic_seeds", "seedName": {"en": "Garlic Seeds", "ko": "마늘 씨앗"}, "unknownSeedName": {"en": "Seed Pods", "ko": "씨앗 꼬투리"}, "oversizedId": "garlic_oversized", "oversizedName": {"en": "Giant Garlic", "ko": "거대한 마늘"}, "plantName": {"en": "Garlic Plant", "ko": "마늘 식물체"}, "description": {"en": "Cloves of garlic pair well with a nice stake. -W", "ko": "질 좋은 스테이크에 곁들여 먹으면 딱이다. -W"}},
  {"id": "onion", "consume": [8, 0, 0], "restore": [0, 4, 4], "seasons": ["spring", "summer", "autumn"], "drinkLevel": "med", "drinkRate": 0.02, "growTime": {"germination": [360, 480], "full": [1920, 3360]}, "seedWeight": 0.5, "name": {"en": "Onion", "ko": "양파"}, "seedId": "onion_seeds", "seedName": {"en": "Onion Seeds", "ko": "양파 씨앗"}, "unknownSeedName": {"en": "Pointy Seeds", "ko": "뾰족한 씨앗"}, "oversizedId": "onion_oversized", "oversizedName": {"en": "Giant Onion", "ko": "거대한 양파"}, "plantName": {"en": "Onion Plant", "ko": "양파 식물체"}, "description": {"en": "A ripe onion plant is enough to bring tears of delight to any gardener. -W", "ko": "그 어떤 정원사라도 잘 익은 양파를 보면 기쁨의 눈물을 감출 수 없다. -W"}},
  {"id": "pepper", "consume": [0, 0, 8], "restore": [4, 4, 0], "seasons": ["summer", "autumn"], "drinkLevel": "low", "drinkRate": 0.0075, "growTime": {"germination": [360, 480], "full": [1920, 3360]}, "seedWeight": 0.5, "name": {"en": "Pepper", "ko": "고추"}, "seedId": "pepper_seeds", "seedName": {"en": "Pepper Seeds", "ko": "고추 씨앗"}, "unknownSeedName": {"en": "Lumpy Seeds", "ko": "혹 난 씨앗"}, "oversizedId": "pepper_oversized", "oversizedName": {"en": "Giant Pepper", "ko": "거대한 고추"}, "plantName": {"en": "Pepper Plant", "ko": "고추 식물체"}, "description": {"en": "A hot pepper plant is the perfect thing to spice up your garden. -W", "ko": "홍고추만큼 정원에 보는 맛을 더하는 것도 없다. -W"}},
  {"id": "pomegranate", "consume": [8, 0, 0], "restore": [0, 4, 4], "seasons": ["spring", "summer"], "drinkLevel": "med", "drinkRate": 0.02, "growTime": {"germination": [360, 480], "full": [1920, 3360]}, "seedWeight": 0.5, "name": {"en": "Pomegranate", "ko": "석류"}, "seedId": "pomegranate_seeds", "seedName": {"en": "Pomegranate Seeds", "ko": "석류 씨앗"}, "unknownSeedName": {"en": "Windblown Seeds", "ko": "깃 달린 씨앗"}, "oversizedId": "pomegranate_oversized", "oversizedName": {"en": "Giant Pomegranate", "ko": "거대한 석류"}, "plantName": {"en": "Pomegranate Branch", "ko": "석류 가지"}, "description": {"en": "Never take the juicy sweetness of a pom for granate. -W", "ko": "절대 석류의 촉촉한 달콤함을 '당'연하게 여기지 말자. -W"}},
];

export const FARM_WEEDS: FarmWeed[] = [
  {"id": "weed_forgetmelots", "seedWeight": 5.0, "consume": [2, 2, 2], "drinkLevel": "low", "drinkRate": 0.0075, "productId": "forgetmelots", "name": {"en": "Forget-Me-Lots", "ko": "건망초"}, "effect": {"en": "Has a tendency to come back when dug up.", "ko": "파내도 파내도 도로 자라는 것만 같다."}},
  {"id": "weed_tillweed", "seedWeight": 0.5, "consume": [2, 2, 2], "drinkLevel": "med", "drinkRate": 0.02, "productId": "tillweed", "name": {"en": "Tillweed", "ko": "뒤엎시라"}, "effect": {"en": "Its roots make a real mess of things, but its flowers are said to have healing properties.", "ko": "뿌리는 주변을 엉망으로 만들지만 꽃에는 약용 성분이 있다고 한다."}},
  {"id": "weed_firenettle", "seedWeight": 0.5, "consume": [2, 2, 2], "drinkLevel": "med", "drinkRate": 0.02, "productId": "firenettles", "name": {"en": "Fire Nettles", "ko": "불쐐기"}, "effect": {"en": "These nettles can cause quite the burning sensation.", "ko": "화끈거리는 감각을 유발할 수 있다."}},
  {"id": "weed_ivy", "seedWeight": 0.5, "consume": [2, 2, 2], "drinkLevel": "med", "drinkRate": 0.02, "productId": null, "name": {"en": "Spiny Bindweed", "ko": "가시올무메꽃"}, "effect": {"en": "Attacks survivors when they disturb a nearby plant", "ko": "주변 식물에게 손을 대는 생존자를 공격한다."}},
];

/** 인게임 식물 도감의 비료 탭 정렬 순서 */
export const FARM_FERTILIZERS: FarmFertilizer[] = [
  {"id": "spoiled_fish_small", "nutrients": [8, 0, 0], "uses": 1, "image": "spoiled_fish_small", "name": {"en": "Spoiled Fish Morsel", "ko": "썩은 생선 조각"}},
  {"id": "spoiled_fish", "nutrients": [16, 0, 0], "uses": 1, "image": "spoiled_fish", "name": {"en": "Spoiled Fish", "ko": "썩은 생선"}},
  {"id": "soil_amender_low", "nutrients": [8, 0, 0], "uses": 1, "image": "soil_amender", "name": {"en": "Growth Formula Starter", "ko": "성장 촉진제 원액"}},
  {"id": "soil_amender_med", "nutrients": [16, 0, 0], "uses": 1, "image": "soil_amender_stale", "name": {"en": "Fermenting Growth Formula", "ko": "발효 중인 성장 촉진제"}},
  {"id": "soil_amender_high", "nutrients": [32, 0, 0], "uses": 1, "image": "soil_amender_spoiled", "name": {"en": "Fermented Growth Formula", "ko": "발효된 성장 촉진제"}},
  {"id": "soil_amender_fermented", "nutrients": [32, 0, 0], "uses": 5, "image": "soil_amender_fermented", "name": {"en": "Super Growth Formula", "ko": "초 성장 촉진제"}},
  {"id": "spoiled_food", "nutrients": [0, 8, 0], "uses": 1, "image": "spoiled_food", "name": {"en": "Rot", "ko": "부패물"}},
  {"id": "rottenegg", "nutrients": [0, 16, 0], "uses": 1, "image": "rottenegg", "name": {"en": "Rotten Egg", "ko": "썩은 알"}},
  {"id": "compost", "nutrients": [0, 24, 0], "uses": 1, "image": "compost", "name": {"en": "Compost", "ko": "퇴비"}},
  {"id": "compostwrap", "nutrients": [24, 32, 24], "uses": 1, "image": "compostwrap", "name": {"en": "Compost Wrap", "ko": "퇴비쌈"}},
  {"id": "poop", "nutrients": [0, 0, 8], "uses": 1, "image": "poop", "name": {"en": "Manure", "ko": "거름"}},
  {"id": "guano", "nutrients": [0, 0, 16], "uses": 1, "image": "guano", "name": {"en": "Guano", "ko": "구아노"}},
  {"id": "fertilizer", "nutrients": [0, 0, 16], "uses": 10, "image": "fertilizer", "name": {"en": "Bucket-o-poop", "ko": "거름통"}},
  {"id": "glommerfuel", "nutrients": [8, 8, 8], "uses": 1, "image": "glommerfuel", "name": {"en": "Glommer's Goop", "ko": "글로머의 점액"}},
  {"id": "treegrowthsolution", "nutrients": [8, 32, 8], "uses": 1, "image": "treegrowthsolution", "name": {"en": "Tree Jam", "ko": "나무 잼"}},
  {"id": "mosquitofertilizer", "nutrients": [12, 12, 12], "uses": 1, "image": "mosquitofertilizer", "name": {"en": "Fertilizzzer", "ko": "왱비료"}},
  {"id": "wx78_foodbrick", "nutrients": [0, 32, 0], "uses": 1, "image": "wx78_foodbrick_wet", "name": {"en": "Nutribrick", "ko": "영양 블록"}},
];

/** range 는 소스 단위, tiles = range / 4 */
export const FARM_TEND_TOOLS: FarmTendTool[] = [
  {"id": "horn", "name": {"en": "Beefalo Horn", "ko": "비팔로 뿔"}, "range": 25, "tiles": 6.25},
  {"id": "gnarwail_horn", "name": {"en": "Gnarwail Horn", "ko": "호각고래 뿔"}, "range": 20, "tiles": 5},
  {"id": "trident", "name": {"en": "Strident Trident", "ko": "시끄러운 삼지창"}, "range": 20, "tiles": 5},
  {"id": "panflute", "name": {"en": "Pan Flute", "ko": "팬플룻"}, "range": 15, "tiles": 3.75},
  {"id": "onemanband", "name": {"en": "One-man Band", "ko": "원 맨 밴드"}, "range": 12, "tiles": 3},
  {"id": "phonograph", "name": {"en": "Gramophone", "ko": "축음기"}, "range": 8, "tiles": 2},
  {"id": "wormwood", "name": {"en": "Wormwood", "ko": "웜우드"}, "range": 4, "tiles": 1},
  {"id": "singingshell_octave3", "name": {"en": "Baritone Shell Bell", "ko": "바리톤 소리고둥"}, "range": 2, "tiles": 0.5},
];

export const FARM_WATER_SOURCES: FarmWaterSource[] = [
  {"id": "wateringcan", "name": {"en": "Empty Watering Can", "ko": "빈 물뿌리개"}, "amount": 25, "uses": 40},
  {"id": "premiumwateringcan", "name": {"en": "Empty Waterfowl Can", "ko": "빈 물부리개"}, "amount": 25, "uses": 160},
  {"id": "waterballoon", "name": {"en": "Waterballoon", "ko": "물풍선"}, "amount": 20, "uses": 1},
  {"id": "ice", "name": {"en": "Ice", "ko": "얼음"}, "amount": 25, "uses": 1},
];

/** 스트레스 합계가 max 이하이면 그 등급 (components/farmplantstress.lua). 마지막은 상한 없음 */
export const FARM_STRESS_GRADES: { grade: FarmStressGradeId; max: number | null }[] = [
  {"grade": "none", "max": 1},
  {"grade": "low", "max": 6},
  {"grade": "moderate", "max": 11},
  {"grade": "high", "max": null},
];

/** quote = 그 항목에 걸린 작물을 살펴볼 때 나오는 윌슨의 대사 */
export const FARM_STRESSORS: { id: FarmStressorId; quote: FarmText }[] = [
  {"id": "nutrients", "quote": {"en": "This poor plant needs nutrients!", "ko": "불쌍한 식물에게 양분을!"}},
  {"id": "moisture", "quote": {"en": "This looks really dehydrated.", "ko": "심히 탈수된 것 같아."}},
  {"id": "killjoys", "quote": {"en": "I might have to do a bit of weeding...", "ko": "김을 조금 매 줄 필요가 있겠어."}},
  {"id": "season", "quote": {"en": "This season is not being kind to this plant.", "ko": "이 계절은 이 식물에게 호의적이지 않아."}},
  {"id": "family", "quote": {"en": "It's my scientific conclusion that this plant seems lonely.", "ko": "내 과학적 결론은 이 식물이 외로움을 탄다는 거야."}},
  {"id": "overcrowding", "quote": {"en": "There are too many plants competing for this small space.", "ko": "작은 공간에서 너무 많은 식물이 경쟁하고 있어."}},
  {"id": "happiness", "quote": {"en": "It's hungry for some good conversation.", "ko": "양질의 대화를 필요로 하고 있어."}},
];
