// ---------------------------------------------------------------------------
// AUTO-GENERATED by scripts/extract-raw-foods.py — DO NOT EDIT.
// Source: DST scripts/prefabs/{veggies,mushrooms,meats,...}.lua + ko.po
// Re-run: python3 scripts/extract-raw-foods.py
// ---------------------------------------------------------------------------

export interface RawFood {
  id: string;
  name: string;            // English name
  nameKo?: string;         // Korean (DST community ko.po)
  foodType: string;        // primary FOODTYPE (lowercase)
  secondaryFoodType?: string;
  hunger: number;          // raw eat — base value (before character/spice modifiers)
  health: number;
  sanity: number;
  perishDays: number;      // perish time in DST days (480s/day)
  image?: string;          // override default `${id}.png`
}

export const rawFoods: RawFood[] = [
  { id: "asparagus", name: "Asparagus", nameKo: "아스파라거스", foodType: "veggie", hunger: 12.5, health: 3, sanity: 0.0, perishDays: 6.0 },
  { id: "barnacle", name: "Barnacle", nameKo: "거북순", foodType: "meat", hunger: 12.5, health: 0.0, sanity: -5, perishDays: 6.0 },
  { id: "batnose", name: "Batnose", nameKo: "벌거숭이 콧구멍", foodType: "meat", hunger: 12.5, health: 3, sanity: -10, perishDays: 6.0 },
  { id: "batwing", name: "Batwing", nameKo: "바틸리스크 날개", foodType: "meat", hunger: 12.5, health: 3, sanity: -10, perishDays: 6.0 },
  { id: "berries", name: "Berries", nameKo: "베리", foodType: "veggie", hunger: 9.375, health: 0.0, sanity: 0.0, perishDays: 6.0 },
  { id: "berries_juicy", name: "Berries Juicy", nameKo: "즙 많은 베리", foodType: "veggie", hunger: 12.5, health: 1, sanity: 0.0, perishDays: 2.0 },
  { id: "bird_egg", name: "Bird Egg", nameKo: "알", foodType: "egg", hunger: 9.375, health: 0.0, sanity: 0.0, perishDays: 10.0 },
  { id: "blue_cap", name: "Blue Cap", nameKo: "파란 버섯", foodType: "veggie", hunger: 12.5, health: 20, sanity: -15, perishDays: 6.0 },
  { id: "butter", name: "Butter", nameKo: "버터", foodType: "dairy", hunger: 25.0, health: 40, sanity: 0.0, perishDays: 40.0 },
  { id: "cactus_meat", name: "Cactus Meat", nameKo: "선인장 과육", foodType: "veggie", hunger: 12.5, health: -3, sanity: -5, perishDays: 10.0 },
  { id: "carrot", name: "Carrot", nameKo: "당근", foodType: "veggie", hunger: 12.5, health: 1, sanity: 0.0, perishDays: 10.0 },
  { id: "cave_banana", name: "Cave Banana", nameKo: "바나나", foodType: "veggie", hunger: 12.5, health: 1, sanity: 0.0, perishDays: 10.0 },
  { id: "corn", name: "Corn", nameKo: "옥수수", foodType: "veggie", hunger: 25.0, health: 3, sanity: 0.0, perishDays: 10.0 },
  { id: "dragonfruit", name: "Dragonfruit", nameKo: "용과", foodType: "veggie", hunger: 9.375, health: 3, sanity: 0.0, perishDays: 6.0 },
  { id: "drumstick", name: "Drumstick", nameKo: "닭다리", foodType: "meat", hunger: 12.5, health: 0.0, sanity: -10, perishDays: 6.0 },
  { id: "durian", name: "Durian", nameKo: "두리안", foodType: "veggie", secondaryFoodType: "monster", hunger: 25.0, health: -3, sanity: -5, perishDays: 10.0 },
  { id: "eggplant", name: "Eggplant", nameKo: "가지", foodType: "veggie", hunger: 25.0, health: 8, sanity: 0.0, perishDays: 10.0 },
  { id: "fig", name: "Fig", nameKo: "무화과", foodType: "veggie", hunger: 12.5, health: 0.0, sanity: 0.0, perishDays: 6.0 },
  { id: "fishmeat", name: "Fishmeat", nameKo: "날생선", foodType: "meat", hunger: 25.0, health: 8, sanity: 0.0, perishDays: 3.0 },
  { id: "fishmeat_small", name: "Fishmeat Small", nameKo: "생선 조각", foodType: "meat", hunger: 12.5, health: 1, sanity: 0.0, perishDays: 3.0 },
  { id: "garlic", name: "Garlic", nameKo: "마늘", foodType: "veggie", hunger: 9.375, health: 0.0, sanity: -10, perishDays: 15.0 },
  { id: "green_cap", name: "Green Cap", nameKo: "녹색 버섯", foodType: "veggie", hunger: 12.5, health: 0.0, sanity: -50, perishDays: 6.0 },
  { id: "honey", name: "Honey", nameKo: "꿀", foodType: "goodies", hunger: 9.375, health: 3, sanity: 0.0, perishDays: 40.0 },
  { id: "kelp", name: "Kelp", nameKo: "다시마 잎", foodType: "veggie", hunger: 9.375, health: -1, sanity: -10, perishDays: 10.0 },
  { id: "meat", name: "Meat", nameKo: "고기", foodType: "meat", hunger: 25.0, health: 1, sanity: -10, perishDays: 6.0 },
  { id: "monstermeat", name: "Monstermeat", nameKo: "괴물고기", foodType: "meat", secondaryFoodType: "monster", hunger: 18.75, health: -20, sanity: -15, perishDays: 6.0 },
  { id: "onion", name: "Onion", nameKo: "양파", foodType: "veggie", hunger: 9.375, health: 0.0, sanity: -10, perishDays: 15.0, image: "quagmire_onion.png" },
  { id: "pepper", name: "Pepper", nameKo: "고추", foodType: "veggie", hunger: 9.375, health: -20, sanity: -15, perishDays: 15.0 },
  { id: "plantmeat", name: "Plantmeat", nameKo: "풀고기", foodType: "meat", hunger: 12.5, health: 0.0, sanity: -10, perishDays: 6.0 },
  { id: "pomegranate", name: "Pomegranate", nameKo: "석류", foodType: "veggie", hunger: 9.375, health: 3, sanity: 0.0, perishDays: 6.0 },
  { id: "potato", name: "Potato", nameKo: "감자", foodType: "veggie", hunger: 12.5, health: -3, sanity: -5, perishDays: 10.0 },
  { id: "red_cap", name: "Red Cap", nameKo: "빨간 버섯", foodType: "veggie", hunger: 12.5, health: -20, sanity: 0.0, perishDays: 6.0 },
  { id: "smallmeat", name: "Smallmeat", nameKo: "고깃조각", foodType: "meat", hunger: 12.5, health: 0.0, sanity: -10, perishDays: 6.0 },
  { id: "tomato", name: "Tomato", nameKo: "토마토란", foodType: "veggie", hunger: 12.5, health: 3, sanity: 0.0, perishDays: 6.0 },
  { id: "watermelon", name: "Watermelon", nameKo: "수박", foodType: "veggie", hunger: 12.5, health: 3, sanity: 5, perishDays: 6.0 },
];
